#pragma once

#include <juce_gui_basics/juce_gui_basics.h>

// Desktop rendering of the MOD pedal's front panel.
//
// The JUCE editor and the two modgui pedals are meant to read as the same
// instrument: same sections in the same order, same rows, same widgets. The
// modgui draws its knobs, switches and faders from pre-rendered film strips
// generated by modgui/tools/generate_assets.py; this class draws the same
// shapes with the same palette and the same proportions, so the two UIs match
// without shipping the PNGs into the JUCE build.
//
// Every constant below is the film-strip geometry from generate_assets.py:
// change one there and change it here.
class NamStackLookAndFeel : public juce::LookAndFeel_V4
{
public:
    // generate_assets.py palette
    static inline const juce::Colour bgTop      { 0xff26282e };
    static inline const juce::Colour bgBottom   { 0xff181a1e };
    static inline const juce::Colour panelEdge  { 0xff0c0d0f };
    static inline const juce::Colour amber      { 0xfff0a030 };
    static inline const juce::Colour amberDim   { 0xff966428 };
    static inline const juce::Colour text       { 0xffd2d2d6 };
    static inline const juce::Colour textDim    { 0xff8c8e94 };
    static inline const juce::Colour knobBody   { 0xff34363c };
    static inline const juce::Colour knobRing   { 0xff121316 };
    static inline const juce::Colour boxFill    { 0xff101114 };
    static inline const juce::Colour boxEdge    { 0xff3a3c42 };
    static inline const juce::Colour switchOff  { 0xff96989e };
    static inline const juce::Colour detent     { 0xff46484e };

    // Set on a Button to make its text left-aligned with the pedal's 6px pad
    // (the file selectors) rather than centred.
    static constexpr const char* alignLeftProperty = "nsAlignLeft";

    // FADER_W of generate_assets.py: the fader is a fixed-width graphic, not a
    // shape that grows with its cell.
    static constexpr float kFaderGraphicWidth = 40.0f;

    NamStackLookAndFeel()
    {
        setColour (juce::ResizableWindow::backgroundColourId, bgBottom);
        setColour (juce::Label::textColourId, text);
        setColour (juce::ComboBox::backgroundColourId, boxFill);
        setColour (juce::ComboBox::outlineColourId, boxEdge);
        setColour (juce::ComboBox::textColourId, amber);
        setColour (juce::ComboBox::arrowColourId, amberDim);
        setColour (juce::PopupMenu::backgroundColourId, boxFill);
        setColour (juce::PopupMenu::textColourId, text);
        setColour (juce::PopupMenu::highlightedBackgroundColourId, amberDim);
        setColour (juce::PopupMenu::highlightedTextColourId, juce::Colours::white);
        setColour (juce::TextButton::buttonColourId, boxFill);
        setColour (juce::TextButton::textColourOffId, amber);
        setColour (juce::TooltipWindow::backgroundColourId, boxFill);
        setColour (juce::TooltipWindow::textColourId, text);
        setColour (juce::TooltipWindow::outlineColourId, boxEdge);
    }

    // draw_knob_frame(): ring, top-lit body, amber arc over 135 deg + 270 deg
    // of sweep, pointer from 0.25 r to 0.78 r, both r/10 thick.
    void drawRotarySlider (juce::Graphics& g, int x, int y, int width, int height,
                           float sliderPos, float startAngle, float endAngle,
                           juce::Slider& slider) override
    {
        const auto bounds = juce::Rectangle<int> (x, y, width, height).toFloat();
        const auto r = juce::jmin (bounds.getWidth(), bounds.getHeight()) * 0.5f - 2.0f;
        if (r <= 0.0f)
            return;

        const auto centre = bounds.getCentre();
        const auto enabled = slider.isEnabled();

        g.setColour (knobRing);
        g.fillEllipse (juce::Rectangle<float> (r * 2.0f, r * 2.0f).withCentre (centre));

        const auto bodyR = r * 0.92f;
        g.setGradientFill ({ knobBody.brighter (0.22f), centre.x, centre.y - bodyR,
                             knobBody.darker (0.28f), centre.x, centre.y + bodyR, false });
        g.fillEllipse (juce::Rectangle<float> (bodyR * 2.0f, bodyR * 2.0f).withCentre (centre));

        const auto angle = startAngle + sliderPos * (endAngle - startAngle);
        const auto thickness = juce::jmax (2.0f, r * 0.10f);
        const auto accent = enabled ? amber : amber.withAlpha (0.35f);

        juce::Path arc;
        arc.addCentredArc (centre.x, centre.y, r * 0.99f, r * 0.99f, 0.0f, startAngle, angle, true);
        g.setColour (accent);
        g.strokePath (arc, { thickness, juce::PathStrokeType::curved, juce::PathStrokeType::rounded });

        juce::Path pointer;
        pointer.startNewSubPath (0.0f, -r * 0.25f);
        pointer.lineTo (0.0f, -r * 0.78f);
        pointer.applyTransform (juce::AffineTransform::rotation (angle).translated (centre));
        g.strokePath (pointer, { thickness, juce::PathStrokeType::curved, juce::PathStrokeType::rounded });
    }

    // draw_fader_frame(): 0.14 w slot inset 10 % top and bottom, a centre
    // detent line at 0 dB, and a 0.62 w x 0.11 h cap with an amber index line.
    void drawLinearSlider (juce::Graphics& g, int x, int y, int width, int height,
                           float sliderPos, float, float,
                           juce::Slider::SliderStyle style, juce::Slider& slider) override
    {
        if (style != juce::Slider::LinearVertical)
        {
            juce::LookAndFeel_V4::drawLinearSlider (g, x, y, width, height, sliderPos,
                                                    0.0f, 0.0f, style, slider);
            return;
        }

        // The pedal's fader film strip is a fixed 40 x 96 graphic centred in a
        // wider cell. Scaling it to the cell width instead would stretch the
        // cap into a bar, so pin the drawing width and centre it.
        const auto w = juce::jmin ((float) width, kFaderGraphicWidth);
        const auto h = (float) height;
        const auto fx = (float) x + ((float) width - w) * 0.5f;
        const auto fy = (float) y;

        const auto slotW = w * 0.14f;
        const auto margin = h * 0.10f;
        g.setColour (knobRing);
        g.fillRoundedRectangle (fx + (w - slotW) * 0.5f, fy + margin, slotW, h - 2.0f * margin,
                                slotW * 0.5f);

        g.setColour (detent);
        g.fillRect (fx + w * 0.18f, fy + h * 0.5f - 0.5f, w * 0.64f, 1.0f);

        const auto capW = w * 0.62f, capH = h * 0.11f;
        const juce::Rectangle<float> cap (fx + (w - capW) * 0.5f, sliderPos - capH * 0.5f, capW, capH);
        g.setColour (knobBody);
        g.fillRoundedRectangle (cap, capH * 0.3f);
        g.setColour (knobRing);
        g.drawRoundedRectangle (cap, capH * 0.3f, 1.0f);
        g.setColour (amber);
        g.fillRect (cap.getX() + 1.0f, cap.getCentreY() - 0.5f, capW - 2.0f, 1.0f);
    }

    // draw_switch_frame(): a slide switch in a square frame, the cap sitting
    // left when off and right when on. The control's name lives in the caption
    // above it, as on the pedal, so the button's own text is not drawn.
    void drawToggleButton (juce::Graphics& g, juce::ToggleButton& button,
                           bool shouldDrawHighlighted, bool) override
    {
        const auto bounds = button.getLocalBounds().toFloat();
        const auto s = juce::jmin (bounds.getWidth(), bounds.getHeight());
        if (s <= 0.0f)
            return;

        const auto frame = juce::Rectangle<float> (s, s).withCentre (bounds.getCentre());
        const auto trackH = s * 0.42f;
        const auto padX = s * 0.08f;
        const juce::Rectangle<float> track (frame.getX() + padX, frame.getCentreY() - trackH * 0.5f,
                                            s - 2.0f * padX, trackH);

        g.setColour (shouldDrawHighlighted ? knobRing.brighter (0.25f) : knobRing);
        g.fillRoundedRectangle (track, trackH * 0.5f);

        const auto inner = s * 0.05f;
        const auto d = trackH - 2.0f * inner;
        const auto on = button.getToggleState();
        const auto capX = on ? track.getRight() - inner - d : track.getX() + inner;

        g.setColour (button.isEnabled() ? (on ? amber : switchOff) : switchOff.withAlpha (0.4f));
        g.fillEllipse (capX, track.getY() + inner, d, d);
    }

    // The pedal's file selector and enumeration boxes: a 4px-radius dark box
    // with a thin edge and amber text.
    void drawComboBox (juce::Graphics& g, int width, int height, bool,
                       int, int, int, int, juce::ComboBox&) override
    {
        const juce::Rectangle<float> r (0.5f, 0.5f, (float) width - 1.0f, (float) height - 1.0f);
        g.setColour (boxFill);
        g.fillRoundedRectangle (r, 4.0f);
        g.setColour (boxEdge);
        g.drawRoundedRectangle (r, 4.0f, 1.0f);

        const auto cx = (float) width - 12.0f, cy = (float) height * 0.5f;
        juce::Path arrow;
        arrow.addTriangle (cx - 4.0f, cy - 2.0f, cx + 4.0f, cy - 2.0f, cx, cy + 3.0f);
        g.setColour (amberDim);
        g.fillPath (arrow);
    }

    void positionComboBoxText (juce::ComboBox& box, juce::Label& label) override
    {
        label.setBounds (6, 0, box.getWidth() - 22, box.getHeight());
        label.setFont (getComboBoxFont (box));
    }

    juce::Font getComboBoxFont (juce::ComboBox&) override
    {
        return juce::Font (juce::FontOptions (11.0f));
    }

    juce::Font getPopupMenuFont() override { return juce::Font (juce::FontOptions (12.0f)); }

    void drawButtonBackground (juce::Graphics& g, juce::Button& button, const juce::Colour&,
                               bool shouldDrawHighlighted, bool shouldDrawDown) override
    {
        const auto r = button.getLocalBounds().toFloat().reduced (0.5f);
        g.setColour (shouldDrawDown ? boxFill.brighter (0.35f)
                                    : (shouldDrawHighlighted ? boxFill.brighter (0.18f) : boxFill));
        g.fillRoundedRectangle (r, 4.0f);
        g.setColour (boxEdge);
        g.drawRoundedRectangle (r, 4.0f, 1.0f);
    }

    void drawButtonText (juce::Graphics& g, juce::TextButton& button, bool, bool) override
    {
        const auto left = (bool) button.getProperties().getWithDefault (alignLeftProperty, false);
        g.setColour (button.isEnabled() ? amber : amber.withAlpha (0.4f));
        g.setFont (juce::Font (juce::FontOptions (11.0f)));
        g.drawText (button.getButtonText(),
                    button.getLocalBounds().reduced (left ? 6 : 4, 0),
                    left ? juce::Justification::centredLeft : juce::Justification::centred,
                    false);
    }
};
